### ISSUE TITLE
Local Cluster with Monotoring and Observability

### ISSUE THREAD

**Issue by federodriguez16** [danunziata/pps_fede_Ferro_2024#18]
**Actividad Nº2 (A2):** Desplegar un entorno de laboratorio local que permita realizar pruebas y experimentos. Para adquirir experiencia práctica en la implementación y configuración de un clúster de Kubernetes y el despliegue de aplicaciones.

## Task
  - [x]  desplegar cluster minikube 2 o mas nodos utiizando driver kvm
  - [x] deployar aplicación python de ejemplo para test de funcionamiento del cluster instalado
  - [x]  deployar infraestructura de monitoreo y observarbilidad basíca:
    - [x] Prometheus, loki, grafana
    - [x] fluenbit

## Entregables
  - Documentación 
  - Códigos versionados

## Referencia
[https://picluster.ricsanfre.com/docs/observability/](https://picluster.ricsanfre.com/docs/observability/)
[https://sdefinitive.net/antrea-observability-part-2-installing-grafana-prometheus-loki-and-fluent-bit/](https://sdefinitive.net/antrea-observability-part-2-installing-grafana-prometheus-loki-and-fluent-bit/)

**Comment by federodriguez16** [comment]
Los archivos para configurar la estructura de logeo se encuentra en el commit e2de7eb
